version: '3'
services:
  # [contianer name]:
  # postres:
  node-app:
    # [build docker image]
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env